### ISSUE TITLE
md2mld is overzealous in its escaping of parentheses

### ISSUE THREAD

**Issue by Niols** [mseri/md2mld#3]
It seems to me that `md2mld` escapes parentheses in Markdown files, resulting in the escaping character `\` showing up in the HTML. If I take a `.md` file:

```
This is an (uninteresting) sentence with (useless) parentheses.
```

and run `md2mld` (version 0.3.0 from OPAM) on it, I get:

```
This is an \(uninteresting\) sentence with \(useless\) parentheses.
```

and compiling such a file with odoc results in the `\(` and `\)` showing up in the HTML. Maybe this has to do with escaping `(*` and `*)`? But then it's a bit overzealous.

**Comment by mseri** [comment]
This may be due to omd, but I do some escaping on the output. Worth to double check.

**Comment by mseri** [comment]
I have looked at the code, I believe this is done by omp. I will try to port the code to omp.2.0.0 and see if it keeps happening. It would be nice to add all these examples to the tests, I had only tested the parts that I needed

**Comment by dmbaturin** [comment]
This issue doesn't seem to exist anymore, with md2mld installed today from opam:

```
$ cat test.md 
This is an (uninteresting) sentence with (useless) parentheses.

$ md2mld ./test.md 
This is an (uninteresting) sentence with (useless) parentheses.

```

**Comment by mseri** [comment]
Thanks
