### ISSUE TITLE
Missing escaping of brackets

### ISSUE THREAD

**Issue by Niols** [mseri/md2mld#4]
`md2mld` (version 0.3.0 from OPAM) does not seem to escape brackets from Markdown. If I take the file:

```
Here is some text [...] and then some more.

Here is a bracket: [

Here is a closing bracket: ]
```

I get an identical `.mld` file. If I then give this file to odoc, it complains and produces an HTML like the following:

![image](https://user-images.githubusercontent.com/5920602/120002186-d7d58a00-bfd4-11eb-81e7-ae625c9122d7.png)

where the brackets have been interpreted as code. It should look like the following in Markdown:

![image](https://user-images.githubusercontent.com/5920602/120002316-fd629380-bfd4-11eb-9b10-9708a3ccc0ae.png)

**Comment by Niols** [comment]
From [the documentation of ocamldoc](https://ocaml.org/manual/ocamldoc.html#ss:ocamldoc-formatting) (odoc and ocamldoc share the same syntax), one escaped strings: *typeset the given string as is; special characters (’{’, ’}’, ’[’, ’]’ and ’@’) must be escaped by a ’\’*.

**Comment by mseri** [comment]
I need to look at how omd parses those. I don't manipulate the `md` in the code, I just get the parsetree from `omd` and use that directly. But it should be possible to escape them when generating the mld.
